#!/bin/bash
# Finish Awesome WM installation 

# -------------- Install Awesome WM Config ------------------------------------
rm -r ~/.config/awesome/widgets/calendar -v
git clone https://github.com/deficient/calendar ~/.config/awesome/widgets/calendar
# -----------------------------------------------------------------------------

