#!/bin/bash
# Finish Awesome WM installation 

# -------------- Install Awesome WM Config ------------------------------------
rm -r ~/.config/awesome/widgets/calendar -v
rm -r ~/.config/awesome/widgets/volume-control -v
git clone https://github.com/deficient/calendar ~/.config/awesome/widgets/calendar
git clone https://github.com/deficient/volume-control \
    ~/.config/awesome/widgets/volume-control
# -----------------------------------------------------------------------------

